# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    oauth_user_provider.class: AppBundle\Security\UserProvider\OAuthUserProvider

services:
    app.twig_extension:
        class: AppBundle\Twig\CarbonExtension
        public: false
        tags:
            - { name: twig.extension }

    oauth_user_provider:
        class: "%oauth_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{facebook: facebook_id}]

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

