<?php

namespace AppBundle\Entity;

/**
 * AnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnswerRepository extends \Doctrine\ORM\EntityRepository
{
    public function count()
    {
        return $this->createQueryBuilder('answer')
            ->select('count(answer.id)')
            ->getQuery()->getSingleScalarResult();
    }

    public function getXMostUseful($maxResults)
    {
        return $this->createQueryBuilder('answer')
            ->select('answer')
            ->orderBy('answer.useful', 'DESC')
            ->setMaxResults($maxResults)
            ->getQuery()->getResult();
    }

    public function getDirectAnswersToQuestion($question)
    {
        return $this->createQueryBuilder('answer')
            ->select('answer')
            ->where(
                $this->getEntityManager()->getExpressionBuilder()
                ->eq('answer.question', ':question')
            )
            ->andWhere(
                $this->getEntityManager()->getExpressionBuilder()
                ->isNull('answer.parent')
            )
            ->setParameter('question', $question)
            ->orderBy('answer.useful', 'DESC')
            ->addOrderBy('answer.createdAt', 'ASC')
            ->getQuery()->getResult();
    }

    public function getNumberOfAnswersToUsersQuestions($user)
    {
        return $this->createQueryBuilder('answer')
            ->select('count(answer)')
            ->innerJoin('answer.question', 'question')
            ->where(
                $this->getEntityManager()->getExpressionBuilder()
                    ->eq('question.author', ':user')
            )
            ->setParameter('user', $user)
            ->getQuery()->getSingleScalarResult();
    }
}
