<?php

namespace AppBundle\Entity;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategoryByQueryString($queryString)
    {
        return $this->createQueryBuilder('category')
            ->select('category')
            ->where('category.name LIKE :string')
            ->setParameter('string', '%'.$queryString.'%')
            ->getQuery()->getResult();
    }

    public function getFirst($countItems)
    {
        return $this->createQueryBuilder('category')
            ->select('category')
            ->setMaxResults($countItems)
            ->getQuery()->getResult();
    }

    public function findBySlug($slug)
    {
        return $this->findBy(['slug' => $slug]);
    }

}
