<?php

namespace AppBundle\Entity;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTopXByQuestionCount($maxResults)
    {
        return $this->createQueryBuilder('tag')
            ->select('tag, count(questions.id) as hidden cnt')
            ->innerJoin('tag.questions', 'questions')
            ->orderBy('cnt', 'DESC')
            ->groupBy('tag')
            ->setMaxResults($maxResults)
            ->getQuery()->getResult();
    }
}
