<?php

namespace AppBundle\Entity;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findUserByQueryString($queryString)
    {
        return $this->createQueryBuilder('user')
            ->select('user')
            ->where('user.username LIKE :string')
            ->setParameter('string', '%'.$queryString.'%')
            ->getQuery()->getResult();
    }

    public function getTopXByKarma($maxResults)
    {
        return $this->createQueryBuilder('user')
            ->select('user')
            ->orderBy('user.karma', 'DESC')
            ->setMaxResults($maxResults)
            ->getQuery()->getResult();
    }
}
